// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// OtpsColumns holds the columns for the "otps" table.
	OtpsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "phone_number", Type: field.TypeString, Unique: true},
		{Name: "otp", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
	}
	// OtpsTable holds the schema information for the "otps" table.
	OtpsTable = &schema.Table{
		Name:       "otps",
		Columns:    OtpsColumns,
		PrimaryKey: []*schema.Column{OtpsColumns[0]},
	}
	// TripsColumns holds the columns for the "trips" table.
	TripsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "drive_id", Type: field.TypeInt, Nullable: true},
		{Name: "start_x", Type: field.TypeFloat64},
		{Name: "start_y", Type: field.TypeFloat64},
		{Name: "end_x", Type: field.TypeFloat64},
		{Name: "end_y", Type: field.TypeFloat64},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "accept", "done", "cancel"}, Default: "pending"},
		{Name: "rate", Type: field.TypeInt, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
	}
	// TripsTable holds the schema information for the "trips" table.
	TripsTable = &schema.Table{
		Name:       "trips",
		Columns:    TripsColumns,
		PrimaryKey: []*schema.Column{TripsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "trips_users_trips",
				Columns:    []*schema.Column{TripsColumns[11]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "phone_number", Type: field.TypeString, Unique: true, Size: 15},
		{Name: "confirmed", Type: field.TypeBool, Default: false},
		{Name: "full_name", Type: field.TypeString},
		{Name: "password", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		OtpsTable,
		TripsTable,
		UsersTable,
	}
)

func init() {
	TripsTable.ForeignKeys[0].RefTable = UsersTable
}
